// Generated by js_of_ocaml 3.10.0
(function(d){"use strict";var
ca=" : flags Open_text and Open_binary are not compatible",ck=982028505,cj="Sys_error",cz="Invalid_argument",b5=0xf0,cy='"',a1=1255,z=0xffff,cw=255,cx=0x800,b4=1026,a0="jsError",u=0x8000,b$=12520,cv=256,ay="[",ci=127,ab=1024,cu="End_of_file",r=0x80,ct="Failure",A=0xff,b2="console",av=")",b3="Undefined_recursive_module",ch=" : flags Open_rdonly and Open_wronly are not compatible",aa=1000,cg="([^/]*)",cs="]",cf=512,cr="; ",b_="Stack_overflow",c="",aX="^",ce=0x7ff0,b1=0xe0,cd=" : file already exists",b9=785140586,P=0x3f,b0=0xdfff,b8="Not_found",N=0xffffff,aZ=0xf,bZ="Assert_failure",y="/",aU="compare: functional value",cc="body",ac=128,co="Sys_blocked_io",cp="fd ",cq=0xdc00,cb="Out_of_memory",b7="Match_failure",l=248,aW=", ",ax=254,aY="index out of bounds",b6="static/",cn="Division_by_zero",bY=250,aV=252,aw="_bigarr02",cl="Selctioner au moins deux cases",cm=1027;function
be(d,b,a){var
e=String.fromCharCode;if(b==0&&a<=4096&&a==d.length)return e.apply(null,d);var
f=c;for(;0<a;b+=ab,a-=ab)f+=e.apply(null,d.slice(b,b+Math.min(a,ab)));return f}function
a7(b){if(d.Uint8Array)var
c=new(d.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
f=b.c,e=f.length,a=0;for(;a<e;a++)c[a]=f.charCodeAt(a);for(e=b.l;a<e;a++)c[a]=0;b.c=c;b.t=4;return c}function
az(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?be(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?be(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)a7(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aA(a){return a}function
a4(a,b,c,d,e){az(aA(a),b,c,d,e);return 0}function
R(a,c,b){b&=A;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}a7(a)}a.c[c]=b;return 0}function
ad(c,a){if(c.fun)return ad(c.fun,a);if(typeof
c!=="function")return c;var
b=c.length|0;if(b===0)return c.apply(null,a);var
e=a.length|0,d=b-e|0;if(d==0)return c.apply(null,a);else
if(d<0)return ad(c.apply(null,a.slice(0,b)),a.slice(b));else
return function(){var
e=arguments.length==0?1:arguments.length,d=new
Array(a.length+e);for(var
b=0;b<a.length;b++)d[b]=a[b];for(var
b=0;b<arguments.length;b++)d[a.length+b]=arguments[b];return ad(c,d)}}function
e_(b,a){if(b==0)return c;if(a.repeat)return a.repeat(b);var
e=c,d=0;for(;;){if(b&1)e+=a;b>>=1;if(b==0)return e;a+=a;d++;if(d==9)a.slice(0,1)}}function
S(a){if(a.t==2)a.c+=e_(a.l-a.c.length,"\0");else
a.c=be(a.c,0,a.c.length);a.t=0}function
V(a){if((a.t&6)!=0)S(a);return a.c}var
fk=Math.log2&&Math.log2(1.1235582092889474E+307)==1020;function
fj(a){if(fk)return Math.floor(Math.log2(a));var
b=0;if(a==0)return-Infinity;if(a>=1)while(a>=2){a/=2;b++}else
while(a<1){a*=2;b--}return b}function
a8(c){var
a=new(d.Float32Array)(1);a[0]=c;var
b=new(d.Int32Array)(a.buffer);return b[0]|0}var
cR=Math.pow(2,-24);function
e6(a){throw a}var
g=[0];function
aG(){e6(g.Division_by_zero)}function
b(b,c,a){this.lo=b&N;this.mi=c&N;this.hi=a&z}b.prototype.caml_custom="_j";b.prototype.copy=function(){return new
b(this.lo,this.mi,this.hi)};b.prototype.ucompare=function(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};b.prototype.compare=function(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};b.prototype.neg=function(){var
a=-this.lo,c=-this.mi+(a>>24),d=-this.hi+(c>>24);return new
b(a,c,d)};b.prototype.add=function(a){var
c=this.lo+a.lo,d=this.mi+a.mi+(c>>24),e=this.hi+a.hi+(d>>24);return new
b(c,d,e)};b.prototype.sub=function(a){var
c=this.lo-a.lo,d=this.mi-a.mi+(c>>24),e=this.hi-a.hi+(d>>24);return new
b(c,d,e)};b.prototype.mul=function(a){var
c=this.lo*a.lo,d=(c*cR|0)+this.mi*a.lo+this.lo*a.mi,e=(d*cR|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
b(c,d,e)};b.prototype.isZero=function(){return(this.lo|this.mi|this.hi)==0};b.prototype.isNeg=function(){return this.hi<<16<0};b.prototype.and=function(a){return new
b(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)};b.prototype.or=function(a){return new
b(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)};b.prototype.xor=function(a){return new
b(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)};b.prototype.shift_left=function(a){a=a&63;if(a==0)return this;if(a<24)return new
b(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
b(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
b(0,0,this.lo<<a-48)};b.prototype.shift_right_unsigned=function(a){a=a&63;if(a==0)return this;if(a<24)return new
b(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
b(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
b(this.hi>>a-48,0,0)};b.prototype.shift_right=function(a){a=a&63;if(a==0)return this;var
d=this.hi<<16>>16;if(a<24)return new
b(this.lo>>a|this.mi<<24-a,this.mi>>a|d<<24-a,this.hi<<16>>a>>>16);var
c=this.hi<<16>>31;if(a<48)return new
b(this.mi>>a-24|this.hi<<48-a,this.hi<<16>>a-24>>16,c&z);return new
b(this.hi<<16>>a-32,c,c)};b.prototype.lsl1=function(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&N;this.lo=this.lo<<1&N};b.prototype.lsr1=function(){this.lo=(this.lo>>>1|this.mi<<23)&N;this.mi=(this.mi>>>1|this.hi<<23)&N;this.hi=this.hi>>>1};b.prototype.udivmod=function(f){var
d=0,c=this.copy(),a=f.copy(),e=new
b(0,0,0);while(c.ucompare(a)>0){d++;a.lsl1()}while(d>=0){d--;e.lsl1();if(c.ucompare(a)>=0){e.lo++;c=c.sub(a)}a.lsr1()}return{quotient:e,modulus:c}};b.prototype.div=function(a){var
b=this;if(a.isZero())aG();var
d=b.hi^a.hi;if(b.hi&u)b=b.neg();if(a.hi&u)a=a.neg();var
c=b.udivmod(a).quotient;if(d&u)c=c.neg();return c};b.prototype.mod=function(b){var
a=this;if(b.isZero())aG();var
d=a.hi;if(a.hi&u)a=a.neg();if(b.hi&u)b=b.neg();var
c=a.udivmod(b).modulus;if(d&u)c=c.neg();return c};b.prototype.toInt=function(){return this.lo|this.mi<<24};b.prototype.toFloat=function(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo};b.prototype.toArray=function(){return[this.hi>>8,this.hi&A,this.mi>>16,this.mi>>8&A,this.mi&A,this.lo>>16,this.lo>>8&A,this.lo&A]};b.prototype.lo32=function(){return this.lo|(this.mi&A)<<24};b.prototype.hi32=function(){return this.mi>>>8&z|this.hi<<16};function
aC(c,d,a){return new
b(c,d,a)}function
aB(a){if(!isFinite(a)){if(isNaN(a))return aC(1,0,ce);return a>0?aC(0,0,ce):aC(0,0,0xfff0)}var
f=a==0&&1/a==-Infinity?u:a>=0?0:u;if(f)a=-a;var
b=fj(a)+1023;if(b<=0){b=0;a/=Math.pow(2,-b4)}else{a/=Math.pow(2,b-cm);if(a<16){a*=2;b-=1}if(b==0)a/=2}var
d=Math.pow(2,24),c=a|0;a=(a-c)*d;var
e=a|0;a=(a-e)*d;var
g=a|0;c=c&aZ|f|b<<4;return aC(g,e,c)}function
ag(a){return a.toArray()}function
cG(c,b,g){c.write(32,b.dims.length);c.write(32,b.kind|b.layout<<8);if(b.caml_custom==aw)for(var
a=0;a<b.dims.length;a++)if(b.dims[a]<z)c.write(16,b.dims[a]);else{c.write(16,z);c.write(32,0);c.write(32,b.dims[a])}else
for(var
a=0;a<b.dims.length;a++)c.write(32,b.dims[a]);switch(b.kind){case
2:case
3:case
12:for(var
a=0;a<b.data.length;a++)c.write(8,b.data[a]);break;case
4:case
5:for(var
a=0;a<b.data.length;a++)c.write(16,b.data[a]);break;case
6:for(var
a=0;a<b.data.length;a++)c.write(32,b.data[a]);break;case
8:case
9:c.write(8,0);for(var
a=0;a<b.data.length;a++)c.write(32,b.data[a]);break;case
7:for(var
a=0;a<b.data.length/2;a++){var
e=ag(b.get(a));for(var
d=0;d<8;d++)c.write(8,e[d])}break;case
1:for(var
a=0;a<b.data.length;a++){var
e=ag(aB(b.get(a)));for(var
d=0;d<8;d++)c.write(8,e[d])}break;case
0:for(var
a=0;a<b.data.length;a++){var
e=a8(b.get(a));c.write(32,e)}break;case
10:for(var
a=0;a<b.data.length/2;a++){var
d=b.get(a);c.write(32,a8(d[1]));c.write(32,a8(d[2]))}break;case
11:for(var
a=0;a<b.data.length/2;a++){var
f=b.get(a),e=ag(aB(f[1]));for(var
d=0;d<8;d++)c.write(8,e[d]);var
e=ag(aB(f[2]));for(var
d=0;d<8;d++)c.write(8,e[d])}break}g[0]=(4+b.dims.length)*4;g[1]=(4+b.dims.length)*8}function
e8(b,a){throw[0,b,a]}function
c1(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>ci)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
bf(f){for(var
k=c,d=c,h,g,i,a,b=0,j=f.length;b<j;b++){g=f.charCodeAt(b);if(g<r){for(var
e=b+1;e<j&&(g=f.charCodeAt(e))<r;e++);if(e-b>cf){d.substr(0,1);k+=d;d=c;k+=f.slice(b,e)}else
d+=f.slice(b,e);if(e==j)break;b=e}a=1;if(++b<j&&((i=f.charCodeAt(b))&-64)==ac){h=i+(g<<6);if(g<b1){a=h-0x3080;if(a<r)a=1}else{a=2;if(++b<j&&((i=f.charCodeAt(b))&-64)==ac){h=i+(h<<6);if(g<b5){a=h-0xe2080;if(a<cx||a>=0xd7ff&&a<0xe000)a=2}else{a=3;if(++b<j&&((i=f.charCodeAt(b))&-64)==ac&&g<0xf5){a=i-0x3c82080+(h<<6);if(a<0x10000||a>0x10ffff)a=3}}}}}if(a<4){b-=a;d+="\ufffd"}else
if(a>z)d+=String.fromCharCode(0xd7c0+(a>>10),cq+(a&0x3FF));else
d+=String.fromCharCode(a);if(d.length>ab){d.substr(0,1);k+=d;d=c}}return k+d}function
B(c,a,b){this.t=c;this.c=a;this.l=b}B.prototype.toString=function(){switch(this.t){case
9:return this.c;default:S(this);case
0:if(c1(this.c)){this.t=9;return this.c}this.t=8;case
8:return this.c}};B.prototype.toUtf16=function(){var
a=this.toString();if(this.t==9)return a;return bf(a)};B.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
B(this.t,a,this.l)};function
cJ(a){return new
B(0,a,a.length)}function
a(a){return cJ(a)}function
bc(c,b){e8(c,a(b))}function
i(a){bc(g.Invalid_argument,a)}function
cE(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
eH(c,f){var
b=d,a;switch(c){case
0:a=b.Float32Array;break;case
1:a=b.Float64Array;break;case
2:a=b.Int8Array;break;case
3:a=b.Uint8Array;break;case
4:a=b.Int16Array;break;case
5:a=b.Uint16Array;break;case
6:a=b.Int32Array;break;case
7:a=b.Int32Array;break;case
8:a=b.Int32Array;break;case
9:a=b.Int32Array;break;case
10:a=b.Float32Array;break;case
11:a=b.Float64Array;break;case
12:a=b.Uint8Array;break}if(!a)i("Bigarray.create: unsupported kind");var
e=new
a(f*cE(c));return e}function
a9(c){var
a=new(d.Int32Array)(1);a[0]=c;var
b=new(d.Float32Array)(a.buffer);return b[0]}function
af(a){return new
b(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
a_(d){var
f=d.lo,g=d.mi,b=d.hi,c=(b&0x7fff)>>4;if(c==2047)return(f|g|b&aZ)==0?b&u?-Infinity:Infinity:NaN;var
e=Math.pow(2,-24),a=(f*e+g)*e+(b&aZ);if(c>0){a+=16;a*=Math.pow(2,c-cm)}else
a*=Math.pow(2,-b4);if(b&u)a=-a;return a}function
a3(b){var
d=b.length,c=1;for(var
a=0;a<d;a++){if(b[a]<0)i("Bigarray.create: negative dimension");c=c*b[a]}return c}function
eT(c,a){return new
b(c&N,c>>>24&A|(a&z)<<8,a>>>16&z)}function
a$(a){return a.hi32()}function
ba(a){return a.lo32()}function
a2(){i(aY)}var
eI=aw;function
J(c,d,b,a){this.kind=c;this.layout=d;this.dims=b;this.data=a}J.prototype.caml_custom=eI;J.prototype.offset=function(b){var
c=0;if(typeof
b==="number")b=[b];if(!(b
instanceof
Array))i("bigarray.js: invalid offset");if(this.dims.length!=b.length)i("Bigarray.get/set: bad number of dimensions");if(this.layout==0)for(var
a=0;a<this.dims.length;a++){if(b[a]<0||b[a]>=this.dims[a])a2();c=c*this.dims[a]+b[a]}else
for(var
a=this.dims.length-1;a>=0;a--){if(b[a]<1||b[a]>this.dims[a])a2();c=c*this.dims[a]+(b[a]-1)}return c};J.prototype.get=function(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return eT(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[ax,e,c];default:return this.data[a]}};J.prototype.set=function(a,b){switch(this.kind){case
7:this.data[a*2+0]=ba(b);this.data[a*2+1]=a$(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;default:this.data[a]=b;break}return 0};J.prototype.fill=function(b){switch(this.kind){case
7:var
c=ba(b),e=a$(b);if(c==e)this.data.fill(c);else
for(var
a=0;a<this.data.length;a++)this.data[a]=a%2==0?c:e;break;case
10:case
11:var
d=b[1],f=b[2];if(d==f)this.data.fill(d);else
for(var
a=0;a<this.data.length;a++)this.data[a]=a%2==0?d:f;break;default:this.data.fill(b);break}};J.prototype.compare=function(b,g){if(this.layout!=b.layout||this.kind!=b.kind){var
e=this.kind|this.layout<<8,f=b.kind|b.layout<<8;return f-e}if(this.dims.length!=b.dims.length)return b.dims.length-this.dims.length;for(var
a=0;a<this.dims.length;a++)if(this.dims[a]!=b.dims[a])return this.dims[a]<b.dims[a]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
c,d;for(var
a=0;a<this.data.length;a++){c=this.data[a];d=b.data[a];if(c<d)return-1;if(c>d)return 1;if(c!=d){if(!g)return NaN;if(c==c)return 1;if(d==d)return-1}}break;case
7:for(var
a=0;a<this.data.length;a+=2){if(this.data[a+1]<b.data[a+1])return-1;if(this.data[a+1]>b.data[a+1])return 1;if(this.data[a]>>>0<b.data[a]>>>0)return-1;if(this.data[a]>>>0>b.data[a]>>>0)return 1}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
a=0;a<this.data.length;a++){if(this.data[a]<b.data[a])return-1;if(this.data[a]>b.data[a])return 1}break}return 0};function
Q(c,d,b,a){this.kind=c;this.layout=d;this.dims=b;this.data=a}Q.prototype=new
J();Q.prototype.offset=function(a){if(typeof
a!=="number")if(a
instanceof
Array&&a.length==1)a=a[0];else
i("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])a2();return a};Q.prototype.get=function(a){return this.data[a]};Q.prototype.set=function(a,b){this.data[a]=b;return 0};Q.prototype.fill=function(a){this.data.fill(a);return 0};function
cC(c,d,a,b){var
e=cE(c);if(a3(a)*e!=b.length)i("length doesn't match dims");if(d==0&&a.length==1&&e==1)return new
Q(c,d,a,b);return new
J(c,d,a,b)}function
T(a){bc(g.Failure,a)}function
cD(b,v,r){var
i=b.read32s();if(i<0||i>16)T("input_value: wrong number of bigarray dimensions");var
p=b.read32s(),j=p&A,o=p>>8&1,h=[];if(r==aw)for(var
a=0;a<i;a++){var
n=b.read16u();if(n==z){var
t=b.read32u(),u=b.read32u();if(t!=0)T("input_value: bigarray dimension overflow in 32bit");n=u}h.push(n)}else
for(var
a=0;a<i;a++)h.push(b.read32u());var
d=a3(h),f=eH(j,d),g=cC(j,o,h,f);switch(j){case
2:for(var
a=0;a<d;a++)f[a]=b.read8s();break;case
3:case
12:for(var
a=0;a<d;a++)f[a]=b.read8u();break;case
4:for(var
a=0;a<d;a++)f[a]=b.read16s();break;case
5:for(var
a=0;a<d;a++)f[a]=b.read16u();break;case
6:for(var
a=0;a<d;a++)f[a]=b.read32s();break;case
8:case
9:var
s=b.read8u();if(s)T("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
a=0;a<d;a++)f[a]=b.read32s();break;case
7:var
e=new
Array(8);for(var
a=0;a<d;a++){for(var
c=0;c<8;c++)e[c]=b.read8u();var
q=af(e);g.set(a,q)}break;case
1:var
e=new
Array(8);for(var
a=0;a<d;a++){for(var
c=0;c<8;c++)e[c]=b.read8u();var
k=a_(af(e));g.set(a,k)}break;case
0:for(var
a=0;a<d;a++){var
k=a9(b.read32s());g.set(a,k)}break;case
10:for(var
a=0;a<d;a++){var
m=a9(b.read32s()),l=a9(b.read32s());g.set(a,[ax,m,l])}break;case
11:var
e=new
Array(8);for(var
a=0;a<d;a++){for(var
c=0;c<8;c++)e[c]=b.read8u();var
m=a_(af(e));for(var
c=0;c<8;c++)e[c]=b.read8u();var
l=a_(af(e));g.set(a,[ax,m,l])}break}v[0]=(4+i)*4;return cC(j,o,h,f)}function
cB(a,b,c){return a.compare(b,c)}function
aF(a,b){return Math.imul(a,b)}function
E(b,a){a=aF(a,0xcc9e2d51|0);a=a<<15|a>>>32-15;a=aF(a,0x1b873593);b^=a;b=b<<13|b>>>32-13;return(b+(b<<2)|0)+(0xe6546b64|0)|0}function
eQ(a,b){a=E(a,ba(b));a=E(a,a$(b));return a}function
cQ(a,b){return eQ(a,aB(b))}function
cF(c){var
b=a3(c.dims),d=0;switch(c.kind){case
2:case
3:case
12:if(b>cv)b=cv;var
e=0,a=0;for(a=0;a+4<=c.data.length;a+=4){e=c.data[a+0]|c.data[a+1]<<8|c.data[a+2]<<16|c.data[a+3]<<24;d=E(d,e)}e=0;switch(b&3){case
3:e=c.data[a+2]<<16;case
2:e|=c.data[a+1]<<8;case
1:e|=c.data[a+0];d=E(d,e)}break;case
4:case
5:if(b>ac)b=ac;var
e=0,a=0;for(a=0;a+2<=c.data.length;a+=2){e=c.data[a+0]|c.data[a+1]<<16;d=E(d,e)}if((b&1)!=0)d=E(d,c.data[a]);break;case
6:if(b>64)b=64;for(var
a=0;a<b;a++)d=E(d,c.data[a]);break;case
8:case
9:if(b>64)b=64;for(var
a=0;a<b;a++)d=E(d,c.data[a]);break;case
7:if(b>32)b=32;b*=2;for(var
a=0;a<b;a++)d=E(d,c.data[a]);break;case
10:b*=2;case
0:if(b>64)b=64;for(var
a=0;a<b;a++)d=cQ(d,c.data[a]);break;case
11:b*=2;case
1:if(b>32)b=32;for(var
a=0;a<b;a++)d=cQ(d,c.data[a]);break}return d}function
eR(a,b){b[0]=4;return a.read32s()}function
e3(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:T("input_value: native integer value too large");default:T("input_value: ill-formed native integer")}}function
eW(c,d){var
b=new
Array(8);for(var
a=0;a<8;a++)b[a]=c.read8u();d[0]=8;return af(b)}function
eV(e,d,b){var
c=ag(d);for(var
a=0;a<8;a++)e.write(8,c[a]);b[0]=8;b[1]=8}function
eS(a,b,c){return a.compare(b)}function
eU(a){return a.lo32()^a.hi32()}var
cP={"_j":{deserialize:eW,serialize:eV,fixed_length:8,compare:eS,hash:eU},"_i":{deserialize:eR,fixed_length:4},"_n":{deserialize:e3,fixed_length:4},"_bigarray":{deserialize:function(a,b){return cD(a,b,"_bigarray")},serialize:cG,compare:cB,hash:cF},"_bigarr02":{deserialize:function(a,b){return cD(a,b,aw)},serialize:cG,compare:cB,hash:cF}};function
a6(a){return cP[a.caml_custom]&&cP[a.caml_custom].compare}function
cM(f,c,d,e){var
b=a6(c);if(b){var
a=d>0?b(c,f,e):b(f,c,e);if(e&&a!=a)return d;if(+a!=+a)return+a;if((a|0)!=0)return a|0}return d}function
aD(a){return a
instanceof
B}function
bb(a){return aD(a)}function
cN(a){if(typeof
a==="number")return aa;else
if(aD(a))return aV;else
if(bb(a))return 1252;else
if(a
instanceof
Array&&a[0]===a[0]>>>0&&a[0]<=cw){var
b=a[0]|0;return b==ax?0:b}else
if(a
instanceof
String)return b$;else
if(typeof
a=="string")return b$;else
if(a
instanceof
Number)return aa;else
if(a&&a.caml_custom)return a1;else
if(a&&a.compare)return 1256;else
if(typeof
a=="function")return 1247;else
if(typeof
a=="symbol")return 1251;return 1001}function
eX(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
cI(a,b){a.t&6&&S(a);b.t&6&&S(b);return a.c<b.c?-1:a.c>b.c?1:0}function
fl(a,b){return cI(a,b)}function
cL(a,b,d){var
e=[];for(;;){if(!(d&&a===b)){var
f=cN(a);if(f==bY){a=a[1];continue}var
g=cN(b);if(g==bY){b=b[1];continue}if(f!==g){if(f==aa){if(g==a1)return cM(a,b,-1,d);return-1}if(g==aa){if(f==a1)return cM(b,a,1,d);return 1}return f<g?-1:1}switch(f){case
247:i(aU);break;case
248:var
c=eX(a[2],b[2]);if(c!=0)return c|0;break;case
249:i(aU);break;case
250:i("equal: got Forward_tag, should not happen");break;case
251:i("equal: abstract value");break;case
252:if(a!==b){var
c=cI(a,b);if(c!=0)return c|0}break;case
253:i("equal: got Double_tag, should not happen");break;case
254:i("equal: got Double_array_tag, should not happen");break;case
255:i("equal: got Custom_tag, should not happen");break;case
1247:i(aU);break;case
1255:var
j=a6(a);if(j!=a6(b))return a.caml_custom<b.caml_custom?-1:1;if(!j)i("compare: abstract value");var
c=j(a,b,d);if(c!=c)return d?-1:c;if(c!==(c|0))return-1;if(c!=0)return c|0;break;case
1256:var
c=a.compare(b,d);if(c!=c)return d?-1:c;if(c!==(c|0))return-1;if(c!=0)return c|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!d)return NaN;if(a==a)return 1;if(b==b)return-1}break;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!d)return NaN;if(a==a)return 1;if(b==b)return-1}break;case
1251:if(a!==b){if(!d)return NaN;return 1}break;case
1252:var
a=V(a),b=V(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
246:case
254:default:if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)e.push(a,b,1);break}}if(e.length==0)return 0;var
h=e.pop();b=e.pop();a=e.pop();if(h+1<a.length)e.push(a,b,h+1);a=a[h];b=b[h]}}function
a5(a,b){return cL(a,b,true)}function
C(a){if(a<0)i("Bytes.create");return new
B(a?2:9,c,a)}function
D(b,a){if(a==0)aG();return b/a|0}function
x(a,b){return+(cL(a,b,false)==0)}var
e5=0;function
U(){return e5++}function
F(a){return a.toUtf16()}if(d.process&&d.process.cwd)var
ae=d.process.cwd().replace(/\\/g,y);else
var
ae="/static";if(ae.slice(-1)!==y)ae+=y;function
eY(a){a=F(a);if(a.charCodeAt(0)!=47)a=ae+a;var
e=a.split(y),b=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(c);break;default:b.push(e[d]);break}b.orig=a;return b}function
eL(a){return new
B(4,a,a.length)}function
fe(f){for(var
g=c,b=g,a,i,d=0,h=f.length;d<h;d++){a=f.charCodeAt(d);if(a<r){for(var
e=d+1;e<h&&(a=f.charCodeAt(e))<r;e++);if(e-d>cf){b.substr(0,1);g+=b;b=c;g+=f.slice(d,e)}else
b+=f.slice(d,e);if(e==h)break;d=e}if(a<cx){b+=String.fromCharCode(0xc0|a>>6);b+=String.fromCharCode(r|a&P)}else
if(a<0xd800||a>=b0)b+=String.fromCharCode(b1|a>>12,r|a>>6&P,r|a&P);else
if(a>=0xdbff||d+1==h||(i=f.charCodeAt(d+1))<cq||i>b0)b+="\xef\xbf\xbd";else{d++;a=(a<<10)+i-0x35fdc00;b+=String.fromCharCode(b5|a>>18,r|a>>12&P,r|a>>6&P,r|a&P)}if(b.length>ab){b.substr(0,1);g+=b;b=c}}return g+b}function
eM(a){var
b=9;if(!c1(a))b=8,a=fe(a);return new
B(b,a,a.length)}function
ai(a){return eM(a)}function
f(a){bc(g.Sys_error,a)}function
e7(a){a=V(a);f(a+": No such file or directory")}function
cH(){i(aY)}function
cK(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
eK(b,a){if(a>>>0>=b.l)cH();return cK(b,a)}function
cT(a){return a.l}function
cA(){}function
h(a){this.data=a}h.prototype=new
cA();h.prototype.truncate=function(a){var
b=this.data;this.data=C(a|0);az(b,0,this.data,0,a)};h.prototype.length=function(){return cT(this.data)};h.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=C(b+a),f=this.data;this.data=e;az(f,0,this.data,0,c)}a4(d,g,this.data,b,a);return 0};h.prototype.read=function(c,a,d,b){var
e=this.length();az(this.data,c,a,d,b);return 0};h.prototype.read_one=function(a){return eK(this.data,a)};h.prototype.close=function(){};h.prototype.constructor=h;function
o(b,a){this.content={};this.root=b;this.lookupFun=a}o.prototype.nm=function(a){return this.root+a};o.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!==0)this.content[b]=new
h(aA(c[1]))}};o.prototype.exists=function(a){if(a==c)return 1;var
d=a+y,e=new
RegExp(aX+d);for(var
b
in
this.content)if(b.match(e))return 1;this.lookup(a);return this.content[a]?1:0};o.prototype.readdir=function(d){var
g=d==c?c:d+y,h=new
RegExp(aX+g+cg),e={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;b.push(a[1])}}return b};o.prototype.is_dir=function(a){var
e=a==c?c:a+y,f=new
RegExp(aX+e+cg),g=[];for(var
d
in
this.content){var
b=d.match(f);if(b)return 1}return 0};o.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};o.prototype.open=function(a,b){if(b.rdonly&&b.wronly)f(this.nm(a)+ch);if(b.text&&b.binary)f(this.nm(a)+ca);this.lookup(a);if(this.content[a]){if(this.is_dir(a))f(this.nm(a)+" : is a directory");if(b.create&&b.excl)f(this.nm(a)+cd);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
h(C(0));return this.content[a]}else
e7(this.nm(a))};o.prototype.register=function(b,a){if(this.content[b])f(this.nm(b)+cd);if(aD(a))this.content[b]=new
h(a);if(bb(a))this.content[b]=new
h(aA(a));else
if(a
instanceof
Array)this.content[b]=new
h(eL(a));else
if(typeof
a==="string")this.content[b]=new
h(cJ(a));else
if(a.toString){var
c=aA(ai(a.toString()));this.content[b]=new
h(c)}else
f(this.nm(b)+" : registering file with invalid content type")};o.prototype.constructor=o;function
ah(a){return cT(a)}function
c0(b,a){return cK(b,a)}function
eG(d){var
c=ah(d),b=new
Array(c),a=0;for(;a<c;a++)b[a]=c0(d,a);return b}function
eF(a){if(a.t!=4)a7(a);return a.c}function
eN(b,a,c){if(a>>>0>=b.l)cH();return R(b,a,c)}function
w(a){this.fs=require("fs");this.fd=a}w.prototype=new
cA();w.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(a){f(a.toString())}};w.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(a){f(a.toString())}};w.prototype.write=function(h,b,c,g){var
a=eG(b);if(!(a
instanceof
d.Uint8Array))a=new(d.Uint8Array)(a);var
e=d.Buffer.from(a);try{this.fs.writeSync(this.fd,e,c,g,h)}catch(a){f(a.toString())}return 0};w.prototype.read=function(i,e,c,h){var
a=eF(e);if(!(a
instanceof
d.Uint8Array))a=new(d.Uint8Array)(a);var
g=d.Buffer.from(a);try{this.fs.readSync(this.fd,g,c,h,i)}catch(a){f(a.toString())}for(var
b=0;b<h;b++)eN(e,c+b,g[c+b]);return 0};w.prototype.read_one=function(c){var
b=new(d.Uint8Array)(1),a=d.Buffer.from(b);try{this.fs.readSync(this.fd,a,0,1,c)}catch(a){f(a.toString())}return a[0]};w.prototype.close=function(){try{this.fs.closeSync(this.fd)}catch(a){f(a.toString())}};w.prototype.constructor=w;function
v(a){this.fs=require("fs");this.root=a}v.prototype.nm=function(a){return this.root+a};v.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(a){f(a.toString())}};v.prototype.readdir=function(a){try{return this.fs.readdirSync(this.nm(a))}catch(a){f(a.toString())}};v.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(a){f(a.toString())}};v.prototype.unlink=function(a){try{var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a))}catch(a){f(a.toString())}return b};v.prototype.open=function(g,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}try{var
d=this.fs.openSync(this.nm(g),b);return new
w(d)}catch(a){f(a.toString())}};v.prototype.rename=function(b,a){try{this.fs.renameSync(this.nm(b),this.nm(a))}catch(a){f(a.toString())}};v.prototype.constructor=v;var
W=ae.match(/[^\/]*\//)[0];function
fg(){return typeof
d.process!=="undefined"&&typeof
d.process.versions!=="undefined"&&typeof
d.process.versions.node!=="undefined"&&d.process.platform!=="browser"}var
aj=[];if(fg())aj.push({path:W,device:new
v(W)});else
aj.push({path:W,device:new
o(W)});aj.push({path:W+b6,device:new
o(W+b6)});function
c2(b){var
f=eY(b),b=f.join(y),e=b+y,c;for(var
d=0;d<aj.length;d++){var
a=aj[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
cO(c,b){var
c=typeof
c=="string"?a(c):c,b=typeof
b=="string"?a(b):b,d=c2(c);if(!d.device.register)T("cannot register file");d.device.register(d.rest,b);return 0}function
eO(){var
b=d.caml_fs_tmp;if(b)for(var
a=0;a<b.length;a++)cO(b[a].name,b[a].content);d.caml_create_file=cO;d.caml_fs_tmp=[];return 0}function
eP(){return 0}var
aE={amp:/&/g,lt:/</g,quot:/\"/g,all:/[&<\"]/};function
cS(a){if(!aE.all.test(a))return a;return a.replace(aE.amp,"&amp;").replace(aE.lt,"&lt;").replace(aE.quot,"&quot;")}var
G=new
Array();function
eZ(d){var
a=G[d];if(!a.opened)f("Cannot flush a closed channel");if(!a.buffer||a.buffer==c)return 0;if(a.fd&&g.fds[a.fd]&&g.fds[a.fd].output){var
b=g.fds[a.fd].output;switch(b.length){case
2:b(d,a.buffer);break;default:b(a.buffer)}}a.buffer=c;return 0}function
cY(e,f){var
b=G[e],d=a(f),c=ah(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
fh(a){var
a=bf(a),b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
fi(a){var
a=bf(a),b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
aH(c,e,d,a){if(g.fds===undefined)g.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?d.length():0;b.flags=a;b.output=e;g.fds[c]=b;if(!g.fd_last_idx||c>g.fd_last_idx)g.fd_last_idx=c;return c}function
fm(c,b,i){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)f(V(c)+ch);if(a.text&&a.binary)f(V(c)+ca);var
d=c2(c),e=d.device.open(d.rest,a),h=g.fd_last_idx?g.fd_last_idx:0;return aH(h+1,cY,e,a)}aH(0,cY,new
h(C(0)));aH(1,fi,new
h(C(0)));aH(2,fh,new
h(C(0)));function
e0(c){var
b=g.fds[c];if(b.flags.wronly)f(cp+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};G[a.fd]=a;return a.fd}function
cU(d){var
b=g.fds[d];if(b.flags.rdonly)f(cp+d+" is readonly");var
a={file:b.file,offset:b.offset,fd:d,opened:true,out:true,buffer:c};G[a.fd]=a;return a.fd}function
e1(){var
b=0;for(var
a=0;a<G.length;a++)if(G[a]&&G[a].opened&&G[a].out)b=[0,G[a].fd,b];return b}function
e2(b,a){if(a==0)aG();return b%a}function
e4(a){if(a
instanceof
Array&&a[0]==a[0]>>>0)return a[0];else
if(aD(a))return aV;else
if(bb(a))return aV;else
if(a
instanceof
Function||typeof
a=="function")return 247;else
if(a&&a.caml_custom)return cw;else
return aa}function
p(b,c,a){if(a&&d.toplevelReloc)b=d.toplevelReloc(a);g[b+1]=c;if(a)g[a]=c}var
cW={};function
e9(a,b){cW[V(a)]=b;return 0}function
e$(){i(aY)}function
fb(b,a){if(a>>>0>=ah(b))e$();return c0(b,a)}function
eJ(a,b){if(a===b)return 1;a.t&6&&S(a);b.t&6&&S(b);return a.c==b.c?1:0}function
fa(a,b){return eJ(a,b)}function
cZ(a,b){return 1-fa(a,b)}function
bd(a){return a}function
fc(){return[0,a("js_of_ocaml")]}function
fd(a){return 0}function
cX(a){return a}function
cV(a){return cW[a]}function
ff(a){if(a
instanceof
Array)return a;if(d.RangeError&&a
instanceof
d.RangeError&&a.message&&a.message.match(/maximum call stack/i))return cX(g.Stack_overflow);if(d.InternalError&&a
instanceof
d.InternalError&&a.message&&a.message.match(/too much recursion/i))return cX(g.Stack_overflow);if(a
instanceof
d.Error&&cV(a0))return[0,cV(a0),a];return[0,g.Failure,ai(String(a))]}function
k(a,b){return a.length==1?a(b):ad(a,[b])}function
n(a,b,c){return a.length==2?a(b,c):ad(a,[b,c])}eO();var
bi=[l,a(cj),-2],bh=[l,a(ct),-3],bg=[l,a(cz),-4],bF=[0,0,[0,1,[0,2,[0,3,[0,4,[0,5,0]]]]]];p(11,[l,a(b3),-12],b3);p(10,[l,a(bZ),-11],bZ);p(9,[l,a(co),-10],co);p(8,[l,a(b_),-9],b_);p(7,[l,a(b7),-8],b7);p(6,[l,a(b8),-7],b8);p(5,[l,a(cn),-6],cn);p(4,[l,a(cu),-5],cu);p(3,bg,cz);p(2,bh,ct);p(1,bi,cj);p(0,[l,a(cb),-1],cb);var
c4=a("\\\\"),c5=a("\\'"),c6=a("\\b"),c7=a("\\t"),c8=a("\\n"),c9=a("\\r"),da=a("nth"),db=a("List.nth"),c$=a("hd"),df=a("Js_of_ocaml__Js.Error"),dm=a("span"),dl=a("td"),dk=a("tr"),dj=a("table"),di=a("div"),dh=a("button"),dg=a("textarea"),dp=a(av),dq=a("find_tag("),dn=a(cc),dF=[0,10,10,10],dG=[1,a("ce n'est pas un de\xcc\x81placement unitaire")],dH=[1,a("ce n'est pas un de\xcc\x81placement multiple")],dI=[1,a(cl)],dJ=[1,a(cl)],dA=[0,0,0,0],dz=[0,0,0],dr=a("Vert"),ds=a("Jaune"),dt=a("Rouge"),du=a("Noir"),dv=a("Bleu"),dw=a("Marron"),dx=a("Libre"),dy=a("Dehors"),dU=a(ay),dV=a(cr),dW=a(ay),dO=a(av),dP=a(aW),dQ=a("Du("),dR=a(av),dS=a(cs),dT=a(ay),dX=a("Sm("),ew=a(c),ex=a(cr),ey=a(c),ev=a(c),ez=a("Le tour est au joueur "),eA=a("Reset"),eB=a("Jouer"),eC=a(cs),eD=a(ay),eE=[0,a("main")],es=a(","),et=[0,1],eu=a(c),d8=a(" marqeur"),d7=[0,a("plateau")],d9=[0,2],d4=a("selected "),d6=a(c),d5=a("case "),d3=[1,a("Selectionne au moins deux cases")],dY=a("pion"),dZ=a(" "),d0=a("pionLibre"),d1=a(c),d2=a(c),dK=a(av),dL=a(aW),dM=a(aW),dN=a("("),ee=a(c),ef=[0,1],eg=[0,a(b2)],ej=a(c),ek=[0,1],el=[0,a("consoleerr")],eo=a("Liste des coups de la partie"),ep=[0,a(b2)];function
aI(a,c,b){return a[1]===c?(a[1]=b,1):0}function
aJ(a){throw[0,bh,a]}U(0);function
j(a){return 0<=a?a:-a|0}function
e(d,c){var
a=ah(d),e=ah(c),b=C(a+e|0);a4(d,0,b,0,a);a4(c,0,b,a,e);return bd(b)}e0(0);cU(1);cU(2);var
aK=[0,function(b){function
a(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{eZ(d)}catch(a){a=ff(a);if(a[1]!==bi)throw a;var
e=a}var
a=c;continue}return 0}}return a(e1(0))}];if(fd(0))for(;;){var
bj=aK[1],c3=[0,1];if(1-aI(aK,bj,function(a,b){return function(c){if(aI(a,1,0))eP(0);return k(b,0)}}(c3,bj)))continue;break}function
ak(b,a){return a?k(b,a[1]):0}U(0);var
c_=fc(0);function
aL(a){return a?a[1]:aJ(c$)}typeof
c_==="number";function
H(c,b){var
a=b;for(;;){if(a){var
d=a[2];k(c,a[1]);var
a=d;continue}return 0}}function
bk(e,d,c){var
b=d,a=c;for(;;){if(a){var
f=a[2],b=n(e,b,a[1]),a=f;continue}return b}}function
bl(b,a){if(a){var
c=a[2],d=a[1];return 0===a5(d[1],b)?c:[0,d,bl(b,c)]}return 0}U(0);U(0);var
bm=[0,0];function
bn(c){for(;;){var
a=bm[1],b=1-aI(bm,a,[0,c,a]);if(b)continue;return b}}var
X=d,bo=null,bp=true,bq=X.Array,br=[l,df,U(0)],aM=[0,br,{}],dd=undefined,de=false,dc=e4(aM)===l?aM:aM[1];e9(a(a0),dc);(function(a){throw a});bn(function(a){return a[1]===br?[0,ai(a[2].toString())]:0});bn(function(a){return a
instanceof
bq?0:[0,ai(a.toString())]});function
aN(c){return function(a){if(1-(a==bo?1:0)){var
d=k(c,a);if(1-(d|0))a.preventDefault();return d}var
e=event,b=k(c,e);if(1-(b|0))e.returnValue=b;return b}}var
s=X.document;function
al(a,b){return a?k(b,a[1]):0}function
am(b,a){return b.createElement(F(a))}function
an(b,a){return am(b,a)}var
bs=[0,b9];function
bt(f,e,d,b){for(;;){if(0===f&&0===e)return am(d,b);var
h=bs[1];if(b9===h){try{var
j=s.createElement('<input name="x">'),k=j.tagName.toLowerCase()==="input"?1:0,m=k?j.name==="x"?1:0:k,i=m}catch(a){var
i=0}var
l=i?ck:-1003883683;bs[1]=l;continue}if(ck<=h){var
a=new
bq();a.push("<",F(b));al(f,function(b){a.push(' type="',cS(b),cy);return 0});al(e,function(b){a.push(' name="',cS(b),cy);return 0});a.push(">");return d.createElement(a.join(c))}var
g=am(d,b);al(f,function(a){return g.type=a});al(e,function(a){return g.name=a});return g}}U(0);X.HTMLElement===dd;function
ao(a){return s.createElement("BR")}function
I(a){return s.createTextNode(F(a))}function
K(b,a){return ak(function(a){return b.className=F(a)},a)}function
L(b,a){return ak(function(a){return b.id=F(a)},a)}function
M(b,a){b.appendChild(a);return 0}function
aO(e,d,c,b){var
a=bt(0,0,s,dh);H(function(b){a.appendChild(b);return 0},b);K(a,e);L(a,d);ak(function(b){return a.onclick=aN(function(a){k(b,0);return bp})},c);return a}function
m(e,d,b,c){var
a=an(s,dl);if(b)a.rowSpan=b[1];H(function(b){return M(a,b)},c);K(a,e);L(a,d);return a}function
Y(d,c,b){var
a=an(s,dk);H(function(b){return M(a,b)},b);K(a,d);L(a,c);return a}function
Z(f,e,d,b){var
a=an(s,di);H(function(b){return M(a,b)},b);ak(function(b){return a.title=F(b)},d);K(a,f);L(a,e);return[0,a,function(b,d){var
e=b?b[1]:b;return e?H(function(b){return M(a,b)},d):(a.innerHTML=c,H(function(b){return M(a,b)},d))}]}function
bu(d,c,b,a){return Z(d,c,b,a)[1]}function
bv(d,c,b){var
a=an(s,dj);K(a,d);L(a,c);H(function(b){return M(a,b)},b);return a}function
bw(d,c,b){var
a=am(s,dm);H(function(b){return M(a,b)},b);K(a,d);L(a,c);return a}function
bx(f,e,c,b,d){var
g=c?c[1]:function(a){return 0},h=b?b[1]:b,a=bt(0,0,s,dg);a.value=F(d);if(h)a.setAttribute("readonly","true");a.oninput=aN(function(b){k(g,ai(a.value));return bp});K(a,f);L(a,e);return[0,a,function(b){return a.value=F(b)}]}var
by=3;function
bz(b){if(typeof
b==="number")switch(b){case
0:return dr;case
1:return ds;case
2:return dt;case
3:return du;case
4:return dv;case
5:return dw;case
6:return dx;default:return dy}else
return 0===b[0]?a(c+b[1]):b[1]}function
bA(b){var
c=b[3],d=b[2],e=b[1],f=-6<=e?1:0;if(f){var
g=e<=6?1:0;if(g){var
h=-3<=d?1:0;if(h){var
i=d<=3?1:0;if(i)var
j=-3<=c?1:0,a=j?c<=3?1:0:j;else
var
a=i}else
var
a=h}else
var
a=g}else
var
a=f;return a}function
ap(g){var
b=g[3],c=g[2],d=g[1],h=0===((d+c|0)+b|0)?1:0;if(h){var
i=-6<=d?1:0;if(i){var
j=d<=6?1:0;if(j){var
k=-3<=c?1:0;if(k){var
l=c<=3?1:0;if(l)var
m=-3<=b?1:0,e=m?b<=3?1:0:m;else
var
e=l}else
var
e=k}else
var
e=j}else
var
e=i;if(e)var
a=e;else{var
n=-3<=d?1:0;if(n){var
o=d<=3?1:0;if(o){var
p=-6<=c?1:0;if(p){var
q=c<=6?1:0;if(q)var
r=-3<=b?1:0,f=r?b<=3?1:0:r;else
var
f=q}else
var
f=p}else
var
f=o}else
var
f=n;if(f)var
a=f;else{var
s=-3<=d?1:0;if(s){var
t=d<=3?1:0;if(t){var
u=-3<=c?1:0;if(u){var
v=c<=3?1:0;if(v)var
w=-6<=b?1:0,a=w?b<=6?1:0:w;else
var
a=v}else
var
a=u}else
var
a=t}else
var
a=s}}}else
var
a=h;return a}function
bB(a,b){if(a){var
c=bB(a[2],b);return[0,a[1],c]}return[0,b,0]}function
bC(b){if(b){var
g=b[1],i=bC(b[2]),c=1,a=g[1],j=g[2];for(;;){var
d=a[3],e=a[2],f=a[1];if(0!==c){var
c=c-1|0,a=[0,-d|0,-f|0,-e|0];continue}var
h=[0,[0,[0,f,e,d],j],i];break}}else
var
h=b;return h}function
aP(b){var
c=b[1];if(!c&&!b[2])return dz;var
a=b[2],d=a?bB(a[2],a[1]):a;return[0,bC(c),d]}function
aQ(b,f){var
d=ap(b);if(d){var
a=f[1],g=[0,b[1],b[2],b[3]];for(;;){if(a){var
e=a[2],c=0===a5(a[1][1],g)?1:0;if(c)return c;var
a=e;continue}return 0}}return d}function
aq(i,h){var
a=i,b=h;for(;;){var
c=a[3],d=a[2],e=a[1];if(0===ap([0,e,d,c]))return 7;var
f=b[1];if(f){var
g=f[1];if(x(g[1],[0,e,d,c]))return g[2];var
a=[0,e,d,c],b=[0,f[2],b[2]];continue}return 6}}var
aR=[0,0,bF],at=bF;a:for(;;){if(at){var
as=aR,q=[0,-6,by,by],dD=at[2],dE=at[1];for(;;){var
dB=j(q[3]),dC=j(q[2]);if(8<=((j(q[1])+dC|0)+dB|0)){var
t=q[1],_=q[2],ar=q[3];if(t===-6)var
O=[0,t+1|0,_,ar-1|0];else{var
bU=0;if(t===-5&&ar===2)var
O=[0,t,_-1|0,ar+1|0];else
bU=1;if(bU){var
bV=0;if(t===-5&&_===2)var
O=[0,t+1|0,_+1|0,ar-2|0];else
bV=1;if(bV){var
bD=q[3],bW=0;if(t===-4&&bD===1)var
O=[0,t,_-1|0,bD+1|0];else
bW=1;if(bW){var
bE=q[3],bX=0;if(t===-4&&bE===2)var
O=[0,t,q[2]-1|0,bE+1|0];else
bX=1;if(bX)var
O=dA}}}}var
as=[0,[0,[0,q,dE],as[1]],as[2]],q=O;continue}var
aR=aP(as),at=dD;continue a}}var
bG=function(a,d,c){var
b=a[2];if(b){var
e=bl(d,a[1]);return[0,[0,[0,c,b[1]],e],b]}return a},bH=function(b,a){return[0,b[1]-a[1]|0,b[2]-a[2]|0,b[3]-a[3]|0]},bI=function(m,u,t){var
d=bH(m,u),c=d[3],b=d[2],a=d[1];if(0===a)var
n=j(b),o=D(c,j(c)),f=[0,[0,0,D(b,j(b)),o],n];else
if(0===b)var
p=j(a),q=D(c,j(c)),f=[0,[0,D(a,j(a)),0,q],p];else
var
r=j(a),s=D(b,j(b)),f=[0,[0,D(a,j(a)),s,0],r];var
g=m,e=f;for(;;){var
h=e[2];if(1===h)return 1;var
i=e[1],k=bH(g,i),l=0===aQ(k,t)?1:0;if(l){var
g=k,e=[0,i,h-1|0];continue}return l}},bJ=function(b){var
a=b;for(;;){if(a){if(a[2]){var
a=a[2];continue}return a[1]}return dF}},bK=function(a){return aL(a)},bL=function(a,b){return 0<a?D(a,b):0===e2(a,b)?D(a,b):D(a,b)-1|0},au=function(b){var
d=e(dL,e(a(c+b[3]),dK)),f=e(dM,e(a(c+b[2]),d));return e(dN,e(a(c+b[1]),f))},aS=function(i,f){var
k=bz(f);if(typeof
f==="number")switch(f){case
6:return n(i,d0,dZ);case
7:return 0;default:var
b=fb(k,0),g=0;if(40<=b)if(92===b)var
d=c4;else
if(ci<=b)g=1;else
g=2;else
if(32<=b)if(39<=b)var
d=c5;else
g=2;else
if(14<=b)g=1;else
switch(b){case
8:var
d=c6;break;case
9:var
d=c7;break;case
10:var
d=c8;break;case
13:var
d=c9;break;default:g=1}switch(g){case
1:var
h=C(4);R(h,0,92);R(h,1,48+(b/100|0)|0);R(h,2,48+((b/10|0)%10|0)|0);R(h,3,48+(b%10|0)|0);var
d=bd(h);break;case
2:var
j=C(1);R(j,0,b);var
d=bd(j);break}return n(i,e(dY,k),d)}else
return 0===f[0]?n(i,d1,a(c+f[1])):n(i,d2,f[1])},bM=function(g,f,b,a,d){if(a===20)return 0;var
h=bL((b-a|0)+3|0,2),c=[0,6-b|0,bL((b+a|0)-15|0,2),h],j=aq(c,d),l=k(f,c),n=k(g,c),i=m(0,0,0,aS(function(b,a){var
c=0,d=[0,I(a),0],f=[0,function(a){return k(l,0)}],g=0,h=n?d4:d6;return[0,aO([0,e(d5,e(h,b))],g,f,d),c]},j));return[0,i,bM(g,f,b,a+1|0,d)]},bN=Z(0,0,0,0),d_=bN[2],d$=bN[1],bO=Z(0,0,0,0),ea=bO[2],eb=bO[1],bP=Z(0,0,0,0),ec=bP[2],ed=bP[1],bQ=bx(eg,0,0,ef,ee),eh=bQ[2],ei=bQ[1],bR=bx(el,0,0,ek,ej),aT=bR[2],em=bR[1],en=[0,ao(0),0],bS=Z(ep,0,0,[0,I(eo),en]),eq=bS[2],er=bS[1],bT=function(V,a,F,aV){var
W=0;if(F){var
S=F[2];if(S){var
aE=0;if(!S[2]){var
B=S[1],C=B[3],T=B[2],u=B[1],D=F[1],E=D[3],U=D[2],v=D[1],aF=0;if((v-u|0)===(T-U|0)&&1===j(v-u|0)&&E===C)aF=1;var
aG=0;if(!aF){var
aH=0;if((v-u|0)===(C-E|0)&&1===j(v-u|0)&&U===T)aH=1;if(!aH){var
aI=0;if((U-T|0)===(C-E|0)&&1===j(E-C|0)&&v===u)aI=1;if(!aI)aG=1}}if(!aG){var
w=[0,[0,B,D]];aE=1}}if(!aE){var
y=F,G=0;for(;;){if(y){var
aJ=[0,y[1],G],y=y[2],G=aJ;continue}var
w=[0,[1,G]];break}}}else
W=1}else
W=1;if(W)var
w=d3;if(0===w[0]){var
d=w[1];if(0===d[0]){var
f=d[2],p=d[1],J=a[2];if(J){var
ad=aq(p,a),ae=6!==ad?1:0;if(ae){var
af=x(ad,J[1]);if(af){var
Z=ap(p),_=Z?ap(f):Z;if(_){var
g=f[3],h=f[2],i=f[1],l=p[3],m=p[2],o=p[1],$=x([0,o,m,l],[0,i,h+1|0,g-1|0]);if($)var
r=$;else{var
aa=x([0,o,m,l],[0,i,h-1|0,g+1|0]);if(aa)var
r=aa;else{var
ab=x([0,o,m,l],[0,i-1|0,h,g+1|0]);if(ab)var
r=ab;else{var
ac=x([0,o,m,l],[0,i+1|0,h,g-1|0]);if(ac)var
r=ac;else
var
aK=x([0,o,m,l],[0,i-1|0,h+1|0,g]),r=aK||x([0,o,m,l],[0,i+1|0,h-1|0,g])}}}var
H=r}else
var
H=_;if(H)var
ag=6===aq(f,a)?1:0,s=ag?bA(f):ag;else
var
s=H}else
var
s=af}else
var
s=ae;var
aM=s?1:s,ah=aM}else
var
ah=J;var
q=0===ah?dG:[0,aP(bG(a,p,f))]}else{var
A=d[1];if(A){var
P=A[1];if(A[2]){var
aD=A[2],Q=[0,P,aD],O=a[2],X=0;if(O){var
ax=aq(bK(Q),a),ay=6!==ax?1:0,az=ay?x(ax,O[1]):ay,Y=0;if(az){var
aA=bA(bJ(Q));if(aA){var
t=Q;for(;;){if(t&&t[2]){var
aw=t[2],b=bK(aw),c=t[1];if(aQ(b,a))var
N=0;else{var
ai=c[1]===b[1]?1:0;if(ai)var
aj=ai;else
var
aN=c[2]===b[2]?1:0,aj=aN||(c[3]===b[3]?1:0);if(0===aj)var
z=0;else
var
K=b[2],ak=b[1],L=c[2],al=c[1],aO=al===ak?L+K|0:L===K?al+ak|0:L+K|0,am=0===(j(aO)%2|0)?1:0,aR=am?[0,[0,(c[1]+b[1]|0)/2|0,(c[2]+b[2]|0)/2|0,(c[3]+b[3]|0)/2|0]]:am,z=aR;if(z){var
M=z[1],an=aQ(M,a);if(an)var
ar=bI(c,M,a),as=ar?bI(M,b,a):ar,at=as?1:as;else
var
at=an;var
av=at}else
var
av=z;var
N=av}if(N){var
t=aw;continue}var
R=N;Y=1}else{var
R=1;Y=1}break}}else
var
aB=aA}else
var
aB=az;if(!Y){var
aC=aB;X=1}}else{var
aC=O;X=1}if(X)var
R=aC;var
q=0===R?dH:[0,aP(bG(a,P,bJ([0,P,aD])))]}else
var
q=dI}else
var
q=dJ}if(0===q[0]){n(V,q[1],0);var
aU=aL(a[2]);n(eq,et,aS(function(f,j){var
g=[0,ao(0),0],h=[0,I(es),g],i=0;if(0===d[0])var
b=e(dP,au(d[2])),a=e(dQ,e(e(au(d[1]),b),dO));else
var
c=d[1],a=e(dX,e(e(bk(function(a,b){var
c=au(b),d=cZ(a,dU)?e(a,dV):dW;return e(d,c)},dT,c),dS),dR));return[0,bw([0,f],0,[0,I(a),i]),h]},aU));return k(aT,eu)}n(V,a,0);return k(aT,q[1])}n(V,a,0);return k(aT,w[1])},$=function(b,a){var
w=bk(function(a,b){var
c=cZ(a,ew)?ex:ey,d=e(c,a);return e(au(b),d)},ev,a);n(d_,0,[0,I(e(ez,bz(aL(b[2])))),0]);var
h=b[2],y=0;function
f(c,d){if(a&&x(c,a[1]))return bT($,b,a,0);return $(b,[0,c,a])}function
g(e){var
b=a;for(;;){if(b){var
d=b[2],c=0===a5(b[1],e)?1:0;if(c)return c;var
b=d;continue}return 0}}function
d(a,b){if(a===13)return 0;var
c=d(a+1|0,b);return[0,Y(0,0,bM(g,f,a,0,b)),c]}var
i=bv(0,d7,d(0,b));function
c(i){var
a=0,c=h;for(;;){if(c){var
a=a+1|0,c=c[2];continue}if(0===(aF(i,a)%6|0)){var
g=aF(i,a)/6|0;if(!(0<=g))throw[0,bg,db];var
b=h,d=g;for(;;){if(b){var
j=b[2],k=b[1];if(0!==d){var
b=j,d=d-1|0;continue}var
f=k}else
var
f=aJ(da);break}}else
var
f=6;return aS(function(b,a){var
c=[0,I(a),0];return[0,bw([0,e(b,d8)],0,c),0]},f)}}var
j=[0,m(0,0,0,0),0],l=[0,m(0,0,0,c(0)),j],o=[0,Y(0,0,[0,m(0,0,0,0),l]),0],p=[0,m(0,0,0,c(5)),0],q=[0,Y(0,0,[0,m(0,0,0,c(1)),p]),o],r=[0,m(0,0,0,c(4)),0],s=[0,m(0,0,d9,[0,i,0]),r],t=[0,Y(0,0,[0,m(0,0,0,c(2)),s]),q],u=[0,m(0,0,0,0),0],v=[0,m(0,0,0,c(3)),u];n(ea,0,[0,bv(0,0,[0,Y(0,0,[0,m(0,0,0,0),v]),t]),y]);var
z=0,A=[0,I(eA),0],B=[0,aO(0,0,[0,function(a){return $(b,0)}],A),z],C=[0,I(eB),0];n(ec,0,[0,aO(0,0,[0,function(c){return bT($,b,a,c)}],C),B]);return k(eh,e(eD,e(w,eC)))};X.onload=aN(function(f){$(aR,0);var
c=[0,ed,[0,ao(0),[0,ei,[0,em,[0,er,0]]]]],d=bu(eE,0,0,[0,eb,[0,bu(0,0,0,[0,d$,[0,ao(0),c]]),0]]),a=X.document.getElementsByTagName(cc).item(0),b=a==bo?aJ(e(dq,e(dn,dp))):a;b.appendChild(d);return de});k(aK[1],0);return}}(function(){return this}()));
